
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: .
    container_name: golang_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:mypass@db:5432/mydb?sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
